name: Building Neko - Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Neko version'
        required: true
        default: '1.0-0-beta_Windows'
        type: string
      changelog:
        description: 'Changelog'
        required: true
        default: ''
        type: string
        
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        ref: neko-windows
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore SimpleFrameworkApp.sln
 
    - name: Build and Publish Web App
      run: msbuild src/NekoForWindows.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: bin\Release\Publish
